@host = http://localhost:5026

### Create a warehouse
POST {{host}}/warehouses
Content-Type: application/json

{
  "code": "WH-001",
  "name": "Main depot"
}

### List warehouses
GET {{host}}/warehouses
